# Generated by Django 4.1.5 on 2023-01-21 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('EmployeeID', models.CharField(max_length=40)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Non-active', 'Non-active')], max_length=100)),
                ('Email', models.CharField(max_length=50)),
                ('Token', models.CharField(max_length=20)),
                ('Token_Expires_at', models.DateTimeField()),
                ('Role', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
                ('Team', models.CharField(choices=[('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('Hr', 'Hr')], max_length=80)),
                ('Batch', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=100)),
                ('Shifts', models.CharField(choices=[('Morning', 'Morning'), ('Night', 'Night')], default='N/A', max_length=70)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Non IT', 'Non It'), ('Mobiles Phones', 'Mobiles Phones')], default='N/A', max_length=100)),
                ('added_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeaveType', models.CharField(max_length=100)),
                ('LeaveBalance', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('From', models.DateTimeField(max_length=10)),
                ('ToDate', models.TextField()),
                ('Duration', models.CharField(max_length=50)),
                ('AppliedTo', models.CharField(max_length=50)),
                ('Notes', models.CharField(max_length=50)),
                ('LeaveStatus', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('Employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empid')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
