# Generated by Django 4.1.5 on 2023-01-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addleave',
            name='ToDate',
            field=models.DateTimeField(),
        ),
    ]
